### ISSUE TITLE
Изменение архитектуры на масштабируемую

### ISSUE THREAD

**Issue by Dimestel** [ExM/BuildRevisionCounter#25]
Это можно сделать посредством разделения приложения на уровни Model, DAL, Api.

**Comment by ExM** [comment]
Почему это приведет к масштабируемости?
К какой именно масштабируемости это приведет?
Как должны соотноситься уровни между собой?
Каково назначение каждого уровня?

**Comment by Dimestel** [comment]
Архитектура станет масштабируемой за счёт того, что не будет сильной связи внутри приложения. Т.е. можно будет без проблем, с минимальными изменениями в проекте вносить изменения. Можно будет как менять отдельные компоненты (в данном случае бд) на другие, т.е. обеспечивать вертикальное масштабирование, так и дополнять систему другими (например ещё одну базу данных), т.е. обеспечить горизонтальное масштабирование.

Разделение компонентов приложения на разные уровни увеличивает надежность и масштабируемость приложения. Это осуществляется за счет возможности применения новых технологий к какому-либо одному уровню без необходимости изменять все решение. Обычная многоуровневая архитектура включает в себя уровни представления, средний уровень, который обычно включает в себя слой доступа к данным (DAL) и бизнес логики (BLL), и уровень данных, который включает в себя базу данных (в данном случае модель). Разделение на уровни может происходить например за счёт разделения на отдельные проекты для каждого уровня.

Уровень представления обеспечивает взаимодействие пользователя с приложением. Может содержать в себе логику приложения. Уровень бизнес логики содержит в себе бизнес логику приложения (если она имеется, в данном случае я считаю в этом уровне нет необходимости, т.к. как таковой бизнес логики тут нет) и осуществляет взаимодействие уровня представления с уровнем доступа к данным. Уровень доступа к данным предоставляет доступ к данным (модели) приложения (в данном случае к бд). Осуществляет взаимодействие уровня с данными либо с уровнем бизнес логики, либо с уровнем представления.

**Comment by ExM** [comment]
"Архитектура станет масштабируемой за счёт того, что не будет сильной связи внутри приложения." - первое не следует из второго.
Вот [определение](https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D1%81%D1%88%D1%82%D0%B0%D0%B1%D0%B8%D1%80%D1%83%D0%B5%D0%BC%D0%BE%D1%81%D1%82%D1%8C), а тут [примеры реализации](http://habrahabr.ru/post/113992/) масштабирования. Слабая связность для этого не требуется.

**Comment by Dimestel** [comment]
Согласен, не следует. Вычеркнем из вышесказанного это предложение.

**Comment by ExM** [comment]
К сожалению вычеркнуть предложение не получится, т.к. это является обоснованием рефакторинга.

Остановимся просто на разделении кода по слоям: DAL, BL и View
Сможете обосновать необходимость разделения по слоям?
Переименуйте Issue.
Как должны соотноситься уровни между собой?
Каково назначение каждого уровня?
Какие классы предлагаете включить в кажый слой?

Будете перименовывать BuildRevisionCounter, то новое имя сделайте BuildRevisionCounter.Web

**Comment by Dimestel** [comment]
Это предложение, лишь часть обоснования. 
По поводу уровней я уже писал выше, продублирую ответ. 
Я может быть не совсем точно выразился назвав ишью "Изменение архитектуры на масштабируемую" - смысл не в том, что появился прирост производительности, а в том что теперь приложение можно масштабировать. Ну а вообще по идее всё чётко: <a href="https://msdn.microsoft.com/ru-ru/library/vstudio/bb384398(v=vs.110).aspx">"Разделение компонентов приложения на разные уровни увеличивает надежность и масштабируемость приложения".</a>
Это осуществляется за счет возможности применения новых технологий к какому-либо одному уровню без необходимости изменять все решение. Обычная многоуровневая архитектура включает в себя уровни представления, средний уровень, который обычно включает в себя слой доступа к данным (DAL) и бизнес логики (BLL), и уровень данных, который включает в себя базу данных (в данном случае модель). Разделение на уровни может происходить например за счёт разделения на отдельные проекты для каждого уровня.

Уровень представления обеспечивает взаимодействие пользователя с приложением. Может содержать в себе логику приложения. Уровень бизнес логики содержит в себе бизнес логику приложения (если она имеется, в данном случае я считаю в этом уровне нет необходимости, т.к. как таковой бизнес логики тут нет) и осуществляет взаимодействие уровня представления с уровнем доступа к данным. Уровень доступа к данным предоставляет доступ к данным (модели) приложения (в данном случае к бд). Осуществляет взаимодействие уровня с данными либо с уровнем бизнес логики, либо с уровнем представления.

По поводу необходимости разделения по слоям. Вот захотите вы бд другую вставить, что тогда придётся делать? Переписывать всё. А если это сложное приложение? В данном приложении запросы к базе используются напрямую в методах апи. Предположим что один и тот же запрос вызывается сто раз, так и придётся переписывать сто раз. В случае разделённых уровней нужно будет только заменить уровни Model и DAL, при это само апи трогать не придётся. А если с базой несколько приложений будет работать? Ну и т.д. 

По поводу включения классов в каждый уровень - в pull request в изменениях предложенных мной и содержится ответ на этот вопрос. Не вижу смысла дублировать эту информацию сюда.

Прошу заметить в моём варианте отсутствует слой с бизнес логикой, т.к. её пока что нет, и по моим прикидкам пока что не предвидится. А я придерживаюсь принципа решения проблем по мере их поступления. 

Насчёт нового имени. Мне кажется, логичнее BuildRevisionCounter переименовать именно в BuildRevisionCounter.Api, потому что должен появиться ещё один проект в котором будут в вэбе редактироваться пользователи (на это есть ишью), а его уже назвать BuildRevisionCounter.Web - как считаете?

**Comment by ExM** [comment]
Не надо ничего дублировать.
Свой первый пост в этом Issue вам надо отредактировать, чтобы точно описать планируемые изменения, а также обосновать их необходимость. 
Из материалов по вашей ссылке можно сделать вывод, что их автор имеет ввиду только вертикальное масштабирование. 
Этот тип масштабирования мы рассматривать не будем.

"Вот захотите вы бд другую вставить, что тогда придётся делать?"
Дельное предложение. Вот задание: https://github.com/ExM/BuildRevisionCounter/issues/28

Итак, мы видимо сошлись на 2х слоях: DAL и View
Вы разбили проект BuildRevisionCounter на три:
- Api - так понимаю это View 
- DAL
- Model - что это? Каково его назначение? Почему это не включено в проект DAL?

Текущее состояние вашего pull-request не позволяет его использовать, хотя бы потому что он устарел. 
Вам следует сделать rebase на актуальное состояние master.

**Comment by Dimestel** [comment]
Model уровень непосредственно с данными, т.е. с базой данных в данном случае. Он вынесен из DAL для отделения доступа к данным от самих данных. Если, допустим, будут добавляться новые базы, возможно удалённые, то DAL будет минимально подвержен изменениям, потому что данные будут вынесены.

**Comment by ExM** [comment]
Я так понял, вместо "Model уровень непосредственно с данными" следует читать "уровень (слой) Model работает непосредственно с данными".
Вынос библиотеки DTO класов не изменил того, что классы работающие с коллекциями остались в DAL, в Model нет логики - он только представляет данные.

Попробуете реализовать #29
