### ISSUE TITLE
Реализовать разграничение доступа к методам

### ISSUE THREAD

**Issue by ExM** [ExM/BuildRevisionCounter#4]
схема: basic-authentication
в БД логин пароль хранить в открытом виде

**Comment by konstantin-uniyatov** [comment]
Приветствую. Прошу пояснить про роль anonymous.
Вижу два варианта реализации:
1. Роль anonymous является обычной ролью, такой как admin. В БД есть пользователи, которым назначена эта роль. Для доступа требуется прохождения аутентификации. Этот вариант смущает тем, как называется роль.
2. Пользователи, не предоставившие логин и пароль, являются anonymous. Этот вариант смущает тем, что для доступа к, например, "GET api/counter/revisionName" пользователь должен быть editor или anonymous, но admin уже не получит доступ. т.е. нужно либо не передавать логин и пароль, либо авторизовываться как editor.

Какой вариант подразумевался?

**Comment by ExM** [comment]
Пользователи, не предоставившие логин и пароль, являются anonymous.
admin должен иметь права не меньше чем anonymous.
Спасибо за вопрос, я поправил описание.

**Comment by konstantin-uniyatov** [comment]
Все равно какая-то странность. Если вариант номер 2, то, например метод api/counter (admin, editor, anonymous). Для доступа к этому методу не нужно предоставлять логин пароль, но если предоставил, то нужно быть admin или editor. Думаю, логично было бы выбрать одни из двух вариантов
1. Не требовать аутентификации для этого метода вообще. т.е. api/counter (anonymous)
2. Запретить анонимный доступ к этому методу. api/counter (admin, editor)

**Comment by ExM** [comment]
Есть еще роль buildserver. Для этой роли и требуется отказать в чтении, если скрипт билд сервера пытается выяснить текущее значение счетчика. В описании нет этого сценария.

**Comment by ExM** [comment]
Все нормально. Спасибо за участие!
